package cn.shuzilm.core;

import android.app.KeyguardManager;
import android.content.ComponentName;
import android.content.ContentProviderClient;
import android.content.Context;
import android.content.Intent;
import android.content.ServiceConnection;
import android.content.SharedPreferences;
import android.content.pm.PackageManager;
import android.content.pm.Signature;
import android.database.Cursor;
import android.net.Uri;
import android.os.Binder;
import android.os.Build;
import android.os.Bundle;
import android.os.IBinder;
import android.os.IInterface;
import android.os.Parcel;
import android.provider.Settings;
import android.text.TextUtils;
import android.util.Base64;
import com.bykv.vk.component.ttvideo.player.MediaPlayer;
import com.oplus.tblplayer.processor.util.EffectConstants;
import com.qq.gdt.action.ActionUtils;
import java.io.File;
import java.lang.reflect.Method;
import java.security.MessageDigest;
import java.util.Random;
import java.util.concurrent.LinkedBlockingQueue;
import kotlin.UByte;

/* JADX INFO: compiled from: SearchBox */
/* JADX INFO: loaded from: classes.dex */
public class AIClient {
    private static long Y = 0;
    private static long Z = 0;

    /* JADX INFO: renamed from: a, reason: collision with root package name */
    static int f2452a = 0;
    public static boolean isf = false;
    private Context aa;
    private String ab = null;
    private final int ac = 0;
    private final int ad = 1;
    private final int ae = 2;
    private final int af = 3;
    private final int ag = 4;
    private final int ah = 5;
    private final int ai = 6;
    private final int aj = 7;
    private final int ak = 8;
    private static int[] b = {MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 228, 188, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 253, 224, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 188, 255, 253, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 0};
    private static int[] c = {MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 224, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 225, 156, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 156, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 219, 212, 219, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 214, 219, 156, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 214, 211, 156, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 223, 213, 156, 214, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 192, 214, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 211, 156, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 213, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 213, 156, 223, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 209, 0};
    private static int[] d = {MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_GET_HW_CODEC_NAME, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 250, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_GET_HW_CODEC_NAME, 240, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 250, 250, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_GET_HW_CODEC_NAME, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 250, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 0};
    private static int[] e = {166, 160, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ASYNC_INIT_CODEC, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 166, 144, 167, 138, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_REAL_TIME, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HURRY_THRESHOLD, 170, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ASYNC_INIT_CODEC, 167, 130, 138, 237, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 162, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 166, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 170, 237, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 166, 170, MediaPlayer.MEDIA_PLAYER_OPTION_SUPER_RES_OPTION, 170, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 166, 167, 170, 237, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HURRY_THRESHOLD, 167, 162, 237, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HURRY_THRESHOLD, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_REAL_TIME, 237, 167, 170, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 162, 237, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_REAL_TIME, 172, 172, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_REAL_TIME, 237, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 172, 160, 0};
    private static int[] f = {218, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 169, 172, 218, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 170, 172, 168, 218, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 166, 170, 217, 168, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 166, 168, 217, 169, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 218, 0};
    private static int[] g = {MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 227, 224, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 218, 0};
    private static int[] h = {234, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 160, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 235, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 239, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 160, 227, 225, 237, 0};
    private static int[] i = {MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 224, 234, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 240, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 240, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 234, 237, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 236, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 192, 202, 213, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 211, 204, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, 208, 202, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 204, 214, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, 206, 204, 192, 0};
    private static int[] j = {209, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 209, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 209, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 210, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 192, 218, 209, 208, 253, 209, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 209, 240, 218, 209, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 154, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 208, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 213, 154, 209, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 209, 208, 218, 209, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 219, 154, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 208, 219, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 154, 217, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 0};
    private static int[] k = {MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 255, 224, 228, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 229, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 255, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 255, 224, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_HW_CONTROL_BY_OPPO, 255, 227, 236, MediaPlayer.MEDIA_PLAYER_OPTION_HW_CONTROL_BY_OPPO, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 0};
    private static int[] l = {MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 207, 208, 212, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 207, 208, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 226, 136, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 207, 208, 212, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 213, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 207, 208, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 136, 207, 211, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 136, 203, 201, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 0};
    private static int[] m = {204, 202, 200, 207, 219, 204, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 224, 205, 192, 204, 202, 192, 223, 204, 237, 224, 135, 204, 202, 192, 223, 219, 204, 218, 205, 192, 204, 202, 192, 223, 204, 205, 135, 192, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 211, 135, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 202, 0};
    private static int[] n = {MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 167, 219, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 170, 168, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 167, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, 166, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 219, 166, 217, 168, 172, 168, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 219, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 0};
    private static int[] o = {MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 213, 211, 206, 209, 209, 212, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, 211, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 200, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 200, 213, 207, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, 210, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, 213, 210, 200, 210, 211, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 209, 0};
    private static int[] p = {233, 255, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 238, 232, 255, 234, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 232, 202, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 255, 238, 233, 227, 201, EffectConstants.ROTATION_DEGREES_180, 233, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, EffectConstants.ROTATION_DEGREES_180, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 232, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 0};
    private static int[] q = {MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 224, 255, MediaPlayer.MEDIA_PLAYER_OPTION_SLOW_PLAY_TIME, 224, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 228, 233, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_SLOW_PLAY_TIME, 253, 255, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 0};
    private static int[] r = {MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 217, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 201, 212, 206, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 233, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 201, 206, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 208, 207, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 208, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 212, 217, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 205, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 0};
    private static int[] s = {MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 202, 214, 204, 0};
    private static int[] t = {MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 209, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 253, 232, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 253, 232, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, 232, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 236, 225, 253, 240, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 0};
    private static int[] u = {226, 228, 238, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 226, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 227, 238, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 233, 226, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 232, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_START_TIME, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 206, 201, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 200, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_START_TIME, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 211, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_START_TIME, 202, 200, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_START_TIME, 201, 200, 206, 211, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 0};
    private static int[] v = {234, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_SUPER_RES_OPTION, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 234, MediaPlayer.MEDIA_PLAYER_OPTION_SUPER_RES_OPTION, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 228, 232, 0};
    private static int[] w = {217, 212, 217, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 206, 206, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_PROBE_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, 233, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_PROBE_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 238, 240, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_PROBE_COUNT, 238, 232, 238, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_PROBE_COUNT, 240, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 0};
    private static int[] x = {MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 213, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 229, 238, 253, 232, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 240, 236, 236, 233, 207, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HIGH_THRESHOLD, 253, 239, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HIGH_THRESHOLD, 239, 233, 239, 253, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_HIGH_THRESHOLD, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 255, 0};
    private static int[] y = {209, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 209, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 240, 253, 240, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 213, 192, 218, 209, 217, 209, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 154, 240, 253, 240, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 213, 192, 218, 209, 217, 209, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 154, 213, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 217, 154, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 213, 154, 217, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 0};
    private static int[] z = {203, 205, 207, 200, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 203, 218, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 239, 202, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 234, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 128, 234, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 234, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 207, 218, 192, 203, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 203, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, 253, 128, 207, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 128, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 207, 128, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 205, 0};
    private static int[] A = {MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 203, 212, 208, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 209, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 203, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 203, 212, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 203, 205, 208, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 204, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 204, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 209, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, 207, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 0};
    private static int[] B = {MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 225, 214, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 156, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 214, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 209, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 214, 156, 214, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 192, 214, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 211, 156, 213, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 223, 211, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 156, 223, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 209, 0};
    private static int[] C = {214, 208, 218, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 214, 224, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 250, 214, 208, 218, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 214, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 250, 157, 214, 208, 218, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 214, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 218, 214, 208, 218, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 214, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 157, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 210, 157, 212, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 192, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 210, 192, 157, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 208, 0};
    private static int[] D = {MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, 200, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 208, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 202, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 211, 204, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 206, 218, 207, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, 214, 217, 202, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 206, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, 206, 204, 192, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, 153, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, 204, 192, 0};
    private static int[] E = {MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 235, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 253, 232, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, 253, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 225, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, 237, 226, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 253, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 0};
    private static int[] F = {218, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 202, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 202, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 214, 205, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_CODEC_ID, 205, 192, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_CODEC_ID, 153, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 205, 204, 192, 0};
    private static int[] G = {205, 209, 204, 232, 211, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 206, 211, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 232, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, 205, 209, 204, 200, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 200, 206, 211, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 207, 192, MediaPlayer.MEDIA_PLAYER_OPTION_SEEK_END_ENABLE, 204, 206, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 0};
    private static int[] H = {234, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_SUPER_RES_OPTION, 239, 226, 239, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_SUPER_RES_OPTION, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 228, 232, 0};
    private static int[] I = {MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 204, 235, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 211, 237, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 211, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 211, 205, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 201, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 205, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 205, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 0};
    private static int[] J = {250, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 233, 237, 250, 236, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, 235, 237, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 235, 236, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 240, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 235, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 236, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 234, 253, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_LOW_THRESHOLD, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 240, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 0};
    private static int[] K = {253, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 255, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 232, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 234, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 232, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 235, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 237, 250, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 0};
    private static int[] L = {237, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 234, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 240, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 236, 235, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 235, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 233, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 234, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 236, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 250, 0};
    private static int[] M = {MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 233, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 211, 237, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 211, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 211, 205, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 201, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 205, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 205, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 0};
    private static int[] N = {MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 201, 214, 210, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 211, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 207, 212, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 206, 201, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 206, 207, 201, 212, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 211, 205, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 206, 213, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_META_DATA_INFO, 205, 207, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 0};
    private static int[] O = {MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 250, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 255, 235, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 237, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 208, 253, 208, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 234, 212, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 240, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 236, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_EGL_NEED_WORKAROUND, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, 250, 0};
    private static int[] P = {250, 237, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 234, 225, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 160, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 253, 253, 160, 225, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, 0};
    private static int[] Q = {202, 214, 208, 208, 0};
    private static int[] R = {212, 200, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 213, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 0};
    private static int[] S = {MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_GET_VIDEODECODER_FPS, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_GET_VIDEODECODER_FPS, 240, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 253, 225, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_GET_VIDEODECODER_FPS, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 0};
    private static int[] T = {238, 232, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 234, 234, 239, 233, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 255, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 236, 255, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, EffectConstants.ROTATION_DEGREES_180, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 234, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, EffectConstants.ROTATION_DEGREES_180, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 0};
    private static int[] U = {207, 201, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 207, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 206, 227, 207, 201, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 207, 238, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_SIDE_DATA, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 218, 218, 223, 217, 206, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, 207, 201, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_PERFER_VIDEO, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 207, 206, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_SIDE_DATA, 206, 203, 218, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 201, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIA_CODEC_SIDE_DATA, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 201, 0};
    private static int[] V = {217, 206, 204, 202, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 202, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 207, 226, 206, 200, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 206, 239, 226, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_ACCURATE_START, 223, 217, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 219, 219, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 207, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 206, 200, MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 206, 207, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_ACCURATE_START, 207, 202, 219, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 200, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_ACCURATE_START, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 200, 0};
    private static int[] W = {204, 202, 192, 223, 219, 204, 250, 237, 224, 232, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 224, 135, 205, 192, 200, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 135, 204, 202, 192, 223, 219, 204, 218, 205, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SET_ORIGINAL_RETRY, 202, 135, 219, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 192, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 135, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, 202, 0};
    private static int[] X = {169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 166, 167, 166, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 168, 169, 219, 169, 166, 168, 217, 172, 169, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 169, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 166, 169, 168, 166, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 166, 0};

    /* JADX INFO: compiled from: SearchBox */
    final class AI implements IInterface {
        private IBinder b;
        private String c;
        private int d;

        public AI(IBinder iBinder, String str, int i) {
            this.b = iBinder;
            this.c = str;
            this.d = i;
        }

        @Override // android.os.IInterface
        public IBinder asBinder() {
            return this.b;
        }

        public String getId() {
            String str;
            Parcel parcelObtain = Parcel.obtain();
            Parcel parcelObtain2 = Parcel.obtain();
            String string = null;
            try {
                str = this.c;
            } catch (Throwable unused) {
                parcelObtain2.recycle();
                parcelObtain.recycle();
            }
            if (str != null && this.d >= 0) {
                parcelObtain.writeInterfaceToken(str);
                this.b.transact(this.d, parcelObtain, parcelObtain2, 0);
                parcelObtain2.readException();
                string = parcelObtain2.readString();
                parcelObtain2.recycle();
                parcelObtain.recycle();
                return string;
            }
            return null;
        }
    }

    /* JADX INFO: compiled from: SearchBox */
    final class AIO implements IInterface {
        private IBinder b;
        private String c;

        public AIO(IBinder iBinder, String str) {
            this.b = iBinder;
            this.c = str;
        }

        @Override // android.os.IInterface
        public IBinder asBinder() {
            return this.b;
        }

        public String getId(String str, String str2, String str3) {
            Parcel parcelObtain = Parcel.obtain();
            Parcel parcelObtain2 = Parcel.obtain();
            String string = null;
            try {
                String str4 = this.c;
                if (str4 == null) {
                    return null;
                }
                parcelObtain.writeInterfaceToken(str4);
                parcelObtain.writeString(str);
                parcelObtain.writeString(str2);
                parcelObtain.writeString(str3);
                this.b.transact(1, parcelObtain, parcelObtain2, 0);
                parcelObtain2.readException();
                string = parcelObtain2.readString();
            } catch (Throwable unused) {
                parcelObtain2.recycle();
                parcelObtain.recycle();
            }
            parcelObtain2.recycle();
            parcelObtain.recycle();
            return string;
        }
    }

    /* JADX INFO: compiled from: SearchBox */
    class AO {
        private int[] b;
        private int[] c;
        private Context d;
        private int[] e;

        private AO(Context context) {
            this.b = new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, 253, 157, 214, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 219, 212, 219, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 214, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 157, 192, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, 214, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 192, 226, 214, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 156, MediaPlayer.MEDIA_PLAYER_OPTION_LOOP_COUNT, 223, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 156, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 219, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 156, 223, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 209, 157, 157, 136, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_QCOM_LOW_LATENCY, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 209, 0};
            this.c = new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 234, 226, 236, 0};
            this.e = new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 207, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 201, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 227, 225, 0};
            this.d = context;
        }

        /* JADX INFO: Access modifiers changed from: private */
        /* JADX WARN: Removed duplicated region for block: B:10:0x0052  */
        /* JADX WARN: Removed duplicated region for block: B:16:0x0061 A[Catch: all -> 0x0070, TryCatch #0 {all -> 0x0070, blocks: (B:4:0x0004, B:6:0x000a, B:12:0x0055, B:14:0x005b, B:16:0x0061, B:17:0x006d, B:9:0x0028), top: B:20:0x0002 }] */
        /*
            Code decompiled incorrectly, please refer to instructions dump.
        */
        public String a(int i) {
            Cursor cursorQuery;
            try {
                if (i == 4) {
                    cursorQuery = Build.VERSION.SDK_INT > 27 ? this.d.getContentResolver().query(Uri.parse(AIClient.this.a(this.b)), null, null, null, null) : null;
                    if (cursorQuery != null && !cursorQuery.isClosed()) {
                        string = cursorQuery.moveToNext() ? cursorQuery.getString(cursorQuery.getColumnIndex(ActionUtils.PAYMENT_AMOUNT)) : null;
                        cursorQuery.close();
                    }
                } else {
                    if (i == 5) {
                        cursorQuery = this.d.getContentResolver().query(Uri.parse(AIClient.this.a(AIClient.D)), null, null, new String[]{AIClient.this.a(this.c)}, null);
                    }
                    if (cursorQuery != null) {
                        if (cursorQuery.moveToNext()) {
                        }
                        cursorQuery.close();
                    }
                }
            } catch (Throwable unused) {
            }
            return string;
        }

        /* JADX INFO: Access modifiers changed from: private */
        public String a() {
            try {
                Uri uri = Uri.parse(AIClient.this.a(AIClient.F));
                int i = Build.VERSION.SDK_INT;
                ContentProviderClient contentProviderClientAcquireContentProviderClient = this.d.getContentResolver().acquireContentProviderClient(uri);
                if (contentProviderClientAcquireContentProviderClient == null) {
                    return null;
                }
                Bundle bundleCall = contentProviderClientAcquireContentProviderClient.call(AIClient.this.a(this.e), null, null);
                if (i >= 24) {
                    contentProviderClientAcquireContentProviderClient.release();
                } else {
                    contentProviderClientAcquireContentProviderClient.release();
                }
                if (bundleCall != null && bundleCall.getInt("code", -1) == 0) {
                    return bundleCall.getString("id");
                }
                return null;
            } catch (Throwable unused) {
                return null;
            }
        }
    }

    /* JADX INFO: compiled from: SearchBox */
    interface HI {

        /* JADX INFO: compiled from: SearchBox */
        public abstract class u extends Binder implements HI {

            /* JADX INFO: compiled from: SearchBox */
            public class d implements HI {

                /* JADX INFO: renamed from: a, reason: collision with root package name */
                private IBinder f2458a;

                public d(IBinder iBinder) {
                    this.f2458a = iBinder;
                }

                @Override // cn.shuzilm.core.AIClient.HI
                public void b(HII.OI oi) {
                    Parcel parcelObtain = Parcel.obtain();
                    Parcel parcelObtain2 = Parcel.obtain();
                    try {
                        parcelObtain.writeInterfaceToken("com.hihonor.cloudservice.oaid.IOAIDService");
                        parcelObtain.writeStrongBinder(oi);
                        this.f2458a.transact(2, parcelObtain, parcelObtain2, 0);
                        parcelObtain2.readException();
                    } finally {
                        try {
                        } finally {
                        }
                    }
                }
            }
        }

        void b(HII.OI oi);
    }

    /* JADX INFO: compiled from: SearchBox */
    final class HNO implements IInterface {
        private IBinder b;

        public HNO(IBinder iBinder) {
            this.b = iBinder;
        }

        @Override // android.os.IInterface
        public IBinder asBinder() {
            return this.b;
        }

        public void getID() {
            try {
                IBinder iBinder = this.b;
                if (iBinder == null) {
                    return;
                }
                Object objQueryLocalInterface = iBinder.queryLocalInterface(AIClient.this.a(AIClient.W));
                ((objQueryLocalInterface == null || !(objQueryLocalInterface instanceof HI.u.d)) ? new HI.u.d(this.b) : (HI.u.d) objQueryLocalInterface).b(AIClient.this.new gid());
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    /* JADX INFO: compiled from: SearchBox */
    public class gid extends HII.OI {
        public gid() {
        }

        @Override // cn.shuzilm.core.AIClient.HII
        public void go(int i, Bundle bundle) {
            try {
                String string = bundle.getString(AIClient.this.a(new int[]{238, 232, 229, 239, 214, 237, 224, 214, 232, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 0}));
                AIClient aIClient = AIClient.this;
                aIClient.a(string, aIClient.a(AIClient.X));
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }

    public AIClient(Context context) {
        this.aa = context;
    }

    private boolean a(String str, int i2) {
        return true;
    }

    private String e() {
        Signature[] signatureArr;
        if (this.ab == null) {
            try {
                signatureArr = this.aa.getPackageManager().getPackageInfo(this.aa.getPackageName(), 64).signatures;
            } catch (Exception unused) {
                signatureArr = null;
            }
            if (signatureArr != null && signatureArr.length > 0) {
                byte[] byteArray = signatureArr[0].toByteArray();
                try {
                    MessageDigest messageDigest = MessageDigest.getInstance("SHA1");
                    if (messageDigest != null) {
                        byte[] bArrDigest = messageDigest.digest(byteArray);
                        StringBuilder sb = new StringBuilder();
                        for (byte b2 : bArrDigest) {
                            sb.append(Integer.toHexString((b2 & UByte.MAX_VALUE) | 256).substring(1, 3));
                        }
                        this.ab = sb.toString();
                    }
                } catch (Exception unused2) {
                }
            }
        }
        return this.ab;
    }

    private void f() {
        try {
            int[] iArr = {255, 232, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 255, 232, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 236, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 224, 210, 224, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 226, 0};
            int[] iArr2 = {226, 239, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 201, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 227, 225, 0};
            int[] iArr3 = {170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 167, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 172, 218, 219, 219, 217, 170, 168, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 169, 169, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 167, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 166, 172, 0};
            Object systemService = this.aa.getSystemService(a(iArr));
            if (systemService == null) {
                return;
            }
            String str = (String) systemService.getClass().getDeclaredMethod(a(iArr2), new Class[0]).invoke(systemService, new Object[0]);
            if (j == null) {
                return;
            }
            a(str, a(iArr3));
        } catch (Exception unused) {
        }
    }

    private void g() {
        try {
            KeyguardManager keyguardManager = (KeyguardManager) this.aa.getSystemService("keyguard");
            a((String) keyguardManager.getClass().getDeclaredMethod(a(new int[]{237, 224, 232, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 224, 232, 253, 235, MediaPlayer.MEDIA_PLAYER_OPTION_NETWORK_TRY_COUNT, 0}), new Class[0]).invoke(keyguardManager, new Object[0]), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 172, 172, 168, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 166, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 168, 167, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 172, 166, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, 218, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 0}));
        } catch (Throwable unused) {
        }
    }

    private void h() {
        try {
            Class<?> cls = Class.forName(a(G));
            a((String) cls.getMethod(a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_JX_CODEC_LOW_LATENCY, 207, MediaPlayer.MEDIA_PLAYER_OPTION_SKIP_AUDIO_GRAPH, 201, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 227, 225, 0}), Context.class).invoke(cls.newInstance(), this.aa), a(new int[]{172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 170, 217, 168, 170, 172, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 169, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 172, 169, 219, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 166, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 0}));
        } catch (Exception unused) {
        }
    }

    private boolean i() {
        if (Y == 0) {
            Y = System.currentTimeMillis() / 1000;
            return true;
        }
        if ((System.currentTimeMillis() / 1000) - Y <= 10) {
            return false;
        }
        Y = System.currentTimeMillis() / 1000;
        return true;
    }

    private boolean j() {
        if (Z == 0) {
            Z = System.currentTimeMillis() / 1000;
            return true;
        }
        if ((System.currentTimeMillis() / 1000) - Z <= 5) {
            return false;
        }
        Z = System.currentTimeMillis() / 1000;
        return true;
    }

    private boolean k() {
        String strD = d(a(o));
        return !TextUtils.isEmpty(strD) && strD.equals("1");
    }

    private boolean l() {
        String strD = d(a(S));
        return !TextUtils.isEmpty(strD) && strD.equalsIgnoreCase(a(R));
    }

    private boolean n() {
        String strD = d(a(P));
        return (TextUtils.isEmpty(strD) || strD.equalsIgnoreCase("unknown")) ? false : true;
    }

    private boolean o() {
        PackageManager packageManager;
        try {
            if (f("<48ID") && (packageManager = this.aa.getPackageManager()) != null) {
                return packageManager.resolveContentProvider(a(E), 0) != null;
            }
            return false;
        } catch (Exception unused) {
            return false;
        }
    }

    private boolean p() {
        try {
            if (!f("=D180")) {
                return false;
            }
            int i2 = Build.VERSION.SDK_INT;
            ContentProviderClient contentProviderClientAcquireUnstableContentProviderClient = this.aa.getContentResolver().acquireUnstableContentProviderClient(Uri.parse(a(F)));
            Bundle bundleCall = contentProviderClientAcquireUnstableContentProviderClient.call("isSupport", null, null);
            if (bundleCall != null) {
                if (i2 >= 24) {
                    contentProviderClientAcquireUnstableContentProviderClient.release();
                } else {
                    contentProviderClientAcquireUnstableContentProviderClient.release();
                }
                if (bundleCall.getInt("code", -1) == 0) {
                    return bundleCall.getBoolean("isSupport", true);
                }
            }
        } catch (Exception unused) {
        }
        return false;
    }

    private void q() {
        Intent intent = new Intent();
        intent.setClassName(a(H), a(I));
        intent.setAction(a(J));
        intent.putExtra(a(K), this.aa.getApplicationInfo().packageName);
        try {
            intent.putExtra(a(L), true);
            this.aa.startService(intent);
        } catch (Exception unused) {
        }
    }

    public void asynAI(int i2) {
        if (isOaidCollectAllowed(i2)) {
            isf = false;
            if (f2452a > 0) {
                return;
            }
            if (k() && i()) {
                a(new AO(this.aa).a(4), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 167, 217, 167, 172, 217, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 219, 166, 170, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 168, 168, 170, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, 218, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 168, 219, 0}));
            }
            try {
                if (f(";4=>E>") && a(a(k), 0)) {
                    a(a(k), a(l), null, a(m), a(n), 1);
                }
            } catch (Exception unused) {
            }
            try {
                if (f("<>C>A>;0") && a(a(k), 0)) {
                    a(a(k), a(l), null, a(m), a(new int[]{168, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 172, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 169, 167, 172, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, 217, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 172, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, 172, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 219, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 218, 169, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, 0}), 1);
                }
            } catch (Exception unused2) {
            }
            try {
                if ((f(">??>") || f("A40;<4")) && a(a(q), 0)) {
                    a(a(q), a(r), a(u), a(t), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 168, 169, 219, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 218, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, 218, 170, 168, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 169, 217, 169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 168, 172, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 167, 170, 170, 0}), 2);
                }
            } catch (Exception unused3) {
            }
            try {
                if (f(">=4?;DB") && a(a(q), 2)) {
                    a(a(q), a(r), a(u), a(t), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 169, 167, 217, 219, 219, 218, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 167, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 217, 167, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 169, 172, 172, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 217, 219, 217, 172, 168, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 168, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 166, 0}), 2);
                }
            } catch (Exception unused4) {
            }
            try {
                if (f("0BDB")) {
                    a(a(x), a(y), a(w), a(z), a(new int[]{217, 170, 217, 218, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 167, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 217, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 169, 217, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 166, 167, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 218, 170, 217, 172, 167, 170, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 0}), 3);
                }
            } catch (Exception unused5) {
            }
            try {
                if (f("B0<BD=6") && a(a(A), 0)) {
                    a(a(A), a(B), null, a(C), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 167, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 219, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 219, 168, 219, 217, 170, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 167, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 172, 218, 217, 218, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, 217, 217, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 0}), 1);
                }
            } catch (Exception unused6) {
            }
            if (o()) {
                a(new AO(this.aa).a(5), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 166, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 167, 172, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 218, 168, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 169, 217, 167, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 170, 217, 169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, 168, 172, 172, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 0}));
            }
            if (p()) {
                a(new AO(this.aa).a(), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 168, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 217, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 219, 218, 168, 170, 167, 169, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 169, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 166, 218, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, 172, 170, 167, 219, 172, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 218, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, 0}));
            }
            try {
                if (f("IC4") && a(a(H), 2)) {
                    q();
                    a(a(H), a(M), a(N), a(O), a(new int[]{167, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 167, 168, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 219, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 168, 166, 169, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 218, 168, 168, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 0}), 6);
                }
            } catch (Exception unused7) {
            }
            try {
                if ((l() || f("5A44<4>B")) && a(a(H), 2)) {
                    q();
                    a(a(H), a(M), a(N), a(O), a(new int[]{169, 172, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 170, 172, 170, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 218, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 217, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 166, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 218, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 168, 169, 166, 217, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 217, 166, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 168, 168, 166, 0}), 6);
                }
            } catch (Exception unused8) {
            }
            try {
                if ((n() || f("BBD8")) && a(a(H), 2)) {
                    q();
                    a(a(H), a(M), a(N), a(O), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 170, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 217, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 169, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 172, 166, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 218, 217, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 166, 172, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 218, 218, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 0}), 6);
                }
            } catch (Exception unused9) {
            }
            try {
                if (f("2>>;?03") && a(a(T), 2)) {
                    a(a(T), a(U), null, a(V), a(new int[]{169, 166, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 217, 167, 168, 217, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 217, 168, 172, 172, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 169, 170, 168, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 219, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 219, 172, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 167, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 217, 168, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 166, 0}), 7);
                }
            } catch (Exception unused10) {
            }
            try {
                String str = Build.MANUFACTURER;
                if ((str.equals("360") || str.equalsIgnoreCase("360UI")) && Build.VERSION.SDK_INT > 25) {
                    a(a(new int[]{234, 253, 255, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 213, 253, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, 238, 234, 253, 203, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, 235, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, MediaPlayer.MEDIA_PLAYER_OPTION_SET_DEFAULT_CODEC_ID, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_INDEX_CACHE, MediaPlayer.MEDIA_PLAYER_OPTION_DISABLE_LOOPER_TIMEOUT, 234, MediaPlayer.MEDIA_PLAYER_OPTION_HW_DEC_DROP_NON_REF, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_TT_HLS_DRM_TOKEN, 0}), a(new int[]{236, 234, 224, 255, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_PROCESSOR_ADDR, 236, 218, 253, 236, 238, 0}), a(new int[]{225, 236, 240, 238, 236, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, 0}), a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 172, 217, 172, 168, 217, 172, 219, 219, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, 217, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 168, 167, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 168, 169, 217, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 170, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 167, 172, 0}));
                }
            } catch (Exception unused11) {
            }
            if (f("4411:") && Build.VERSION.SDK_INT > 27) {
                f();
            }
            try {
                int[] iArr = {233, 228, MediaPlayer.MEDIA_PLAYER_OPTION_GET_AUDIO_DEVICE_OPENED_TIME, 255, 226, 227, 226, 229, 228, 229, MediaPlayer.MEDIA_PLAYER_OPTION_GET_AUDIO_DEVICE_OPENED_TIME, 224, 226, 238, 0};
                if (f("7>=>A") && b(a(iArr), 2)) {
                    int[] iArr2 = {MediaPlayer.MEDIA_PLAYER_OPTION_ALOG_WRITE_FUNC_ADDR, 234, 226, 236, 0};
                    String string = Settings.Secure.getString(this.aa.getContentResolver(), a(iArr2));
                    if (string == null || string.isEmpty()) {
                        string = Settings.Global.getString(this.aa.getContentResolver(), a(iArr2));
                    }
                    if (string == null || string.isEmpty()) {
                        a(a(iArr), "", a(new int[]{MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, 237, 233, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 200, 255, 210, 250, 212, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, 211, MediaPlayer.MEDIA_PLAYER_OPTION_ASYNC_INIT_CODEC, 255, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_ASYNC_INIT_CODEC, 233, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RENDER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_FRAG_RANGE, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ASYNC_INIT_CODEC, MediaPlayer.MEDIA_PLAYER_OPTION_HIJACK_EXIT, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SEEK_INTERRUPT, 0}), "", "", 8);
                    } else {
                        a(string, a(X));
                    }
                }
            } catch (Exception e2) {
                e2.printStackTrace();
            }
            g();
            if (m()) {
                h();
            }
            try {
                if (b(a(h), 0)) {
                    a(a(h), a(i), a(h), a(j), a(new int[]{219, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 218, 170, 167, 218, 170, 170, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, 219, 170, 167, 172, 167, 219, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 217, 219, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_BIT_RATE, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 168, 217, 218, 219, 217, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 0}), 0);
                }
            } catch (Exception unused12) {
            }
            try {
                if (b(a(b), 0) && j()) {
                    if (!f(">??>") && !f("E8E>") && !f(">=4?;DB")) {
                        a(a(b), a(c), a(d), a(e), a(f), 0);
                    } else if (!a(a(f))) {
                        Thread.sleep(60L);
                        if (new Random().nextInt(3) == 0) {
                            a(a(b), a(c), a(d), a(e), a(f), 0);
                        }
                    }
                }
            } catch (Exception unused13) {
            }
            isf = true;
            f2452a++;
        }
    }

    public String cm(String str) {
        return n() ? a(Q) : l() ? a(R) : str;
    }

    public boolean isOaidCollectAllowed(int i2) {
        String strB;
        if (i2 == 2) {
            return true;
        }
        String strA = a(new int[]{166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 167, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 166, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_BITRATE, 219, 218, 166, 167, 166, 218, 218, 169, 168, 170, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_SWITCH_COUNT, 169, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, MediaPlayer.MEDIA_PLAYER_OPTION_ABR_AVERAGE_PLAY_SPEED, 218, 167, 168, MediaPlayer.MEDIA_PLAYER_OPTION_AUDIO_DECODER_ERROR, 170, MediaPlayer.MEDIA_PLAYER_OPTION_FASTOPEN_LIVE_STREAM, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, 170, 0});
        if (a(strA) && (strB = b(strA)) != null && !strB.isEmpty()) {
            if (i2 == 1) {
                if (!strB.startsWith(a(new int[]{205, MediaPlayer.MEDIA_PLAYER_OPTION_LIVE_STREAM_MAX_CACHE_SECONDS, MediaPlayer.MEDIA_PLAYER_ADAPTIVE_WORK_AROUND_MODE, 192, 205, 219, 205, 211, MediaPlayer.MEDIA_PLAYER_OPTION_ENABLE_SOLOPLAY, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 0}))) {
                    return false;
                }
                c(strA);
                return true;
            }
            if (i2 == 3) {
                return !strB.startsWith(a(new int[]{MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_PRE_DECODE_AUTO_PAUSE, 240, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_DECODER_ERROR, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 205, 219, MediaPlayer.MEDIA_PLAYER_OPTION_VIDEO_RANGE_SIZE, MediaPlayer.MEDIA_PLAYER_OPTION_MEDIACODEC_DROP_NONREF, 0}));
            }
        }
        return i2 != 1;
    }

    public boolean m() {
        try {
            return Class.forName(a(G)).newInstance() != null;
        } catch (Exception unused) {
            return false;
        }
    }

    private String b(String str) {
        try {
            SharedPreferences sharedPreferences = this.aa.getSharedPreferences(this.aa.getPackageName() + a(g), 0);
            return sharedPreferences != null ? sharedPreferences.getString(str, "") : "";
        } catch (Throwable unused) {
            return "";
        }
    }

    private boolean c(String str, int i2) {
        if (str == null) {
            return false;
        }
        try {
            return this.aa.getPackageManager().checkPermission(com.kuaishou.weapon.p0.g.f7481a, str) == 0;
        } catch (Exception unused) {
            return false;
        }
    }

    private String d(String str) {
        if (str == null) {
            return null;
        }
        try {
            Class<?> cls = Class.forName(a(p));
            return (String) cls.getMethod("get", String.class, String.class).invoke(cls, str, "unknown");
        } catch (Exception unused) {
            return null;
        }
    }

    private boolean a(String str) {
        SharedPreferences sharedPreferences = this.aa.getSharedPreferences(this.aa.getPackageName() + a(g), 0);
        if (sharedPreferences != null) {
            return sharedPreferences.contains(str);
        }
        return false;
    }

    /* JADX INFO: Access modifiers changed from: private */
    public static void b(final LinkedBlockingQueue linkedBlockingQueue, final IBinder iBinder) {
        try {
            new Thread(new Runnable() { // from class: cn.shuzilm.core.AIClient.1
                @Override // java.lang.Runnable
                public void run() {
                    try {
                        linkedBlockingQueue.put(iBinder);
                    } catch (Exception unused) {
                    }
                }
            }).start();
        } catch (Exception unused) {
        }
    }

    private String c(String str) {
        try {
            SharedPreferences sharedPreferences = this.aa.getSharedPreferences(this.aa.getPackageName() + a(g), 0);
            if (sharedPreferences == null) {
                return "";
            }
            SharedPreferences.Editor editorEdit = sharedPreferences.edit();
            editorEdit.remove(str);
            editorEdit.apply();
            return "";
        } catch (Throwable unused) {
            return "";
        }
    }

    private boolean b(String str, int i2) {
        String str2;
        String absolutePath;
        int iLastIndexOf;
        boolean zExists = false;
        try {
            File externalFilesDir = this.aa.getExternalFilesDir(null);
            if (externalFilesDir == null || (iLastIndexOf = (absolutePath = externalFilesDir.getAbsolutePath()).lastIndexOf("/data/")) == -1) {
                str2 = "";
            } else {
                str2 = absolutePath.substring(0, iLastIndexOf) + "/data/";
            }
            zExists = new File(str2 + str).exists();
        } catch (Exception unused) {
        }
        if (zExists) {
            return true;
        }
        return c(str, i2);
    }

    /* JADX INFO: Access modifiers changed from: private */
    public synchronized void a(String str, String str2) {
        if (str != null && str2 != null) {
            if (!str.isEmpty() && !str2.isEmpty()) {
                try {
                    byte[] bArr = new byte[3];
                    byte[] bArrEncode = Base64.encode(str.getBytes(), 0);
                    bArr[1] = 115;
                    if (bArrEncode != null) {
                        try {
                            byte[] bArr2 = new byte[bArrEncode.length];
                            int i2 = 0;
                            for (byte b2 : bArrEncode) {
                                if (33 < b2 && b2 < 126) {
                                    bArr2[i2] = b2;
                                    i2++;
                                }
                            }
                            bArr[0] = 75;
                            byte[] bArr3 = new byte[i2];
                            System.arraycopy(bArr2, 0, bArr3, 0, i2);
                            bArr[2] = 90;
                            if (i2 < 256) {
                                str = new String(bArr, "UTF-8") + new String(bArr3, "UTF-8");
                            }
                        } catch (Exception unused) {
                        }
                    }
                    SharedPreferences sharedPreferences = this.aa.getSharedPreferences(this.aa.getPackageName() + a(g), 0);
                    if (sharedPreferences != null) {
                        String string = sharedPreferences.getString(str2, "a");
                        if (string != null && string.equals(str)) {
                            return;
                        }
                        SharedPreferences.Editor editorEdit = sharedPreferences.edit();
                        editorEdit.putString(str2, str);
                        editorEdit.apply();
                    }
                } catch (Exception unused2) {
                }
            }
        }
    }

    private boolean f(String str) {
        if (str == null) {
            return false;
        }
        try {
            String str2 = Build.MANUFACTURER;
            if (str2 == null) {
                return false;
            }
            String upperCase = str2.toUpperCase();
            String strE = e(str);
            if (strE != null) {
                return upperCase.equals(strE);
            }
            return false;
        } catch (Exception unused) {
            return false;
        }
    }

    private synchronized String e(String str) {
        String str2 = null;
        if (str == null) {
            return null;
        }
        try {
            byte[] bytes = str.getBytes();
            int length = bytes.length;
            for (int i2 = 0; i2 < length; i2++) {
                bytes[i2] = (byte) (bytes[i2] + 17);
            }
            str2 = new String(bytes);
        } catch (Exception unused) {
        }
        return str2;
    }

    /* JADX INFO: compiled from: SearchBox */
    public interface HII extends IInterface {
        void go(int i, Bundle bundle);

        /* JADX INFO: compiled from: SearchBox */
        public abstract class OI extends Binder implements HII {

            /* JADX INFO: renamed from: a, reason: collision with root package name */
            String f2459a = "com.hihonor.cloudservice.oaid.IOAIDCallBack";

            public OI() {
                attachInterface(this, "com.hihonor.cloudservice.oaid.IOAIDCallBack");
            }

            @Override // android.os.Binder
            public boolean onTransact(int i, Parcel parcel, Parcel parcel2, int i2) {
                if (i == 2) {
                    try {
                        parcel.enforceInterface(this.f2459a);
                        go(parcel.readInt(), parcel.readInt() == 0 ? null : (Bundle) Bundle.CREATOR.createFromParcel(parcel));
                        parcel2.writeNoException();
                        return true;
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                }
                return super.onTransact(i, parcel, parcel2, i2);
            }

            @Override // android.os.IInterface
            public IBinder asBinder() {
                return this;
            }
        }
    }

    /* JADX INFO: compiled from: SearchBox */
    final class AC implements ServiceConnection {

        /* JADX INFO: renamed from: a, reason: collision with root package name */
        boolean f2454a;
        private final LinkedBlockingQueue b;

        private AC() {
            this.f2454a = false;
            this.b = new LinkedBlockingQueue(1);
        }

        public IBinder getBinder() {
            if (this.f2454a) {
                throw new IllegalStateException();
            }
            this.f2454a = true;
            return (IBinder) this.b.take();
        }

        @Override // android.content.ServiceConnection
        public void onServiceConnected(ComponentName componentName, IBinder iBinder) {
            AIClient.b(this.b, iBinder);
        }

        @Override // android.content.ServiceConnection
        public void onServiceDisconnected(ComponentName componentName) {
        }
    }

    private void a(String str, String str2, String str3, String str4) {
        IBinder iBinder;
        try {
            Method declaredMethod = Class.forName(str).getDeclaredMethod(str2, String.class);
            if (declaredMethod == null || (iBinder = (IBinder) declaredMethod.invoke(null, str3)) == null) {
                return;
            }
            Parcel parcelObtain = Parcel.obtain();
            Parcel parcelObtain2 = Parcel.obtain();
            try {
                iBinder.transact(4, parcelObtain, parcelObtain2, 0);
                String string = parcelObtain2.readString();
                if (string != null && !string.isEmpty()) {
                    a(string, str4);
                }
                parcelObtain.recycle();
            } catch (Exception unused) {
                parcelObtain.recycle();
            } catch (Throwable th) {
                parcelObtain.recycle();
                parcelObtain2.recycle();
                throw th;
            }
            parcelObtain2.recycle();
        } catch (Throwable unused2) {
        }
    }

    /* JADX WARN: Multi-variable type inference failed */
    private void a(String str, String str2, String str3, String str4, String str5, int i2) {
        Intent intent;
        Intent intent2;
        AI ai;
        try {
            Intent intent3 = null;
            AC ac = new AC();
            if (i2 == 0) {
                Intent intent4 = new Intent(str2);
                intent4.setPackage(str3);
                intent3 = intent4;
            } else {
                if (i2 == 1) {
                    intent2 = new Intent();
                    intent2.setClassName(str, str2);
                } else if (i2 == 2) {
                    intent3 = new Intent();
                    intent3.setComponent(new ComponentName(str, str2));
                    intent3.setAction(str3);
                } else {
                    if (i2 == 3) {
                        intent = new Intent();
                        intent.setAction(str3);
                        intent.setComponent(new ComponentName(str, str));
                    } else if (i2 == 6) {
                        intent3 = new Intent();
                        intent3.setClassName(str, str2);
                        intent3.setAction(str3);
                        intent3.putExtra(a(K), this.aa.getApplicationInfo().packageName);
                    } else if (i2 == 7) {
                        intent2 = new Intent();
                        intent2.setComponent(new ComponentName(str, str2));
                    } else if (i2 == 8) {
                        intent = new Intent();
                        intent.setAction(str3);
                        intent.setPackage(str);
                    }
                    intent3 = intent;
                }
                intent3 = intent2;
            }
            if (this.aa.bindService(intent3, ac, 1)) {
                try {
                    if (i2 == 2) {
                        try {
                            Thread.sleep(100L);
                        } catch (Exception e2) {
                            e2.printStackTrace();
                        }
                        String id = new AIO(ac.getBinder(), str4).getId(this.aa.getPackageName(), e(), a(s));
                        if (id != null) {
                            a(id, str5);
                        }
                    } else if (i2 == 8) {
                        new HNO(ac.getBinder()).getID();
                    } else {
                        if (i2 == 3 || i2 == 6) {
                            ai = new AI(ac.getBinder(), str4, 3);
                        } else if (i2 == 7) {
                            ai = new AI(ac.getBinder(), str4, 2);
                        } else {
                            ai = new AI(ac.getBinder(), str4, 1);
                        }
                        String id2 = ai.getId();
                        if (id2 != null) {
                            a(id2, str5);
                        }
                    }
                } catch (Throwable unused) {
                }
                this.aa.unbindService(ac);
            }
        } catch (Throwable unused2) {
        }
    }

    /* JADX INFO: Access modifiers changed from: private */
    public synchronized String a(int[] iArr) {
        String string = null;
        if (iArr == null) {
            return null;
        }
        try {
            int length = iArr.length;
            StringBuilder sb = new StringBuilder();
            int i2 = length + 126;
            for (int i3 = 0; i3 < length; i3++) {
                if (i3 != 0) {
                    sb.append(Character.toString((char) (iArr[(length - i3) - 1] ^ i2)));
                }
            }
            string = sb.toString();
        } catch (Exception unused) {
        }
        return string;
    }
}
