package com.kwad.sdk.core.b.a;

import com.ksad.annotation.invoker.InvokeBy;
import com.kwad.components.core.innerEc.InnerEcUserLoginBindInfo;
import com.kwad.components.core.innerEc.qcpx.ReceiveQcpxBody;
import com.kwad.components.core.video.a.d;
import com.kwad.components.core.webview.a.a;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveMessageListener;
import com.kwad.components.core.webview.jshandler.WebCardRegisterLiveShopListener;
import com.kwad.components.core.webview.jshandler.WebCardVideoPositionHandler;
import com.kwad.components.core.webview.jshandler.a;
import com.kwad.components.core.webview.jshandler.a.a;
import com.kwad.components.core.webview.jshandler.a.e;
import com.kwad.components.core.webview.jshandler.a.f;
import com.kwad.components.core.webview.jshandler.ag;
import com.kwad.components.core.webview.jshandler.ah;
import com.kwad.components.core.webview.jshandler.aj;
import com.kwad.components.core.webview.jshandler.ak;
import com.kwad.components.core.webview.jshandler.an;
import com.kwad.components.core.webview.jshandler.ao;
import com.kwad.components.core.webview.jshandler.ap;
import com.kwad.components.core.webview.jshandler.as;
import com.kwad.components.core.webview.jshandler.at;
import com.kwad.components.core.webview.jshandler.au;
import com.kwad.components.core.webview.jshandler.av;
import com.kwad.components.core.webview.jshandler.ay;
import com.kwad.components.core.webview.jshandler.ba;
import com.kwad.components.core.webview.jshandler.be;
import com.kwad.components.core.webview.jshandler.bf;
import com.kwad.components.core.webview.jshandler.bg;
import com.kwad.components.core.webview.jshandler.bj;
import com.kwad.components.core.webview.jshandler.e;
import com.kwad.components.core.webview.jshandler.f;
import com.kwad.components.core.webview.jshandler.g;
import com.kwad.components.core.webview.jshandler.h;
import com.kwad.components.core.webview.jshandler.i;
import com.kwad.components.core.webview.jshandler.j;
import com.kwad.components.core.webview.jshandler.l;
import com.kwad.components.core.webview.jshandler.m;
import com.kwad.components.core.webview.jshandler.q;
import com.kwad.components.core.webview.jshandler.u;
import com.kwad.components.core.webview.jshandler.v;
import com.kwad.components.core.webview.jshandler.y;
import com.kwad.components.core.webview.tachikoma.b.h;
import com.kwad.components.core.webview.tachikoma.b.u;
import com.kwad.components.core.webview.tachikoma.b.x;
import com.kwad.sdk.j.a;
import com.kwad.sdk.kgeo.KGeoInfo;
import com.kwad.sdk.mobileid.UaidInfo;
import com.kwad.sdk.resourceCache.model.WarmUpReportMessage;

/* JADX INFO: compiled from: SearchBox */
/* JADX INFO: loaded from: classes9.dex */
public final class dc {
    @InvokeBy(invokerClass = gu.class, methodId = "registerHolder")
    public static void Je() {
        gu.Jf().put(com.kwad.components.core.innerEc.followuser.b.class, new er());
        gu.Jf().put(com.kwad.components.core.webview.a.b.class, new ih());
        gu.Jf().put(ReceiveQcpxBody.class, new jg());
        gu.Jf().put(a.C0628a.class, new jy());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.m.class, new hb());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.z.class, new mn());
        gu.Jf().put(WebCardVideoPositionHandler.VideoPosition.class, new mm());
        gu.Jf().put(e.b.class, new fu());
        gu.Jf().put(com.kwad.components.core.page.c.a.class, new ha());
        gu.Jf().put(d.a.class, new mh());
        gu.Jf().put(x.a.class, new bo());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.v.class, new ku());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.i.class, new em());
        gu.Jf().put(j.a.class, new fg());
        gu.Jf().put(au.a.class, new bk());
        gu.Jf().put(ap.b.class, new gq());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.a.class, new o());
        gu.Jf().put(a.C0564a.class, new cg());
        gu.Jf().put(an.a.class, new df());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.n.class, new hq());
        gu.Jf().put(KGeoInfo.class, new gv());
        gu.Jf().put(at.a.class, new bh());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.y.class, new mj());
        gu.Jf().put(e.a.class, new ka());
        gu.Jf().put(i.a.class, new ff());
        gu.Jf().put(f.a.class, new cl());
        gu.Jf().put(ba.a.class, new hd());
        gu.Jf().put(com.kwad.components.core.webview.a.c.class, new ij());
        gu.Jf().put(com.kwad.components.core.b.b.class, new gy());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.j.class, new fj());
        gu.Jf().put(be.a.class, new mo());
        gu.Jf().put(ao.b.class, new fl());
        gu.Jf().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.AdLiveMessageItemInfo.class, new ae());
        gu.Jf().put(l.a.class, new fi());
        gu.Jf().put(h.a.class, new fe());
        gu.Jf().put(ag.a.class, new iy());
        gu.Jf().put(com.kwad.components.core.l.a.class, new v());
        gu.Jf().put(ay.a.class, new mr());
        gu.Jf().put(u.b.class, new kv());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.x.class, new mf());
        gu.Jf().put(bj.a.class, new gt());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.k.class, new gr());
        gu.Jf().put(m.a.class, new gd());
        gu.Jf().put(y.a.class, new x());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.w.class, new mc());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.r.class, new kd());
        gu.Jf().put(com.kwad.components.core.offline.moitor.d.class, new mb());
        gu.Jf().put(aj.a.class, new md());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.u.class, new kh());
        gu.Jf().put(u.a.class, new lf());
        gu.Jf().put(h.b.class, new ix());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.c.class, new bq());
        gu.Jf().put(bf.a.class, new lo());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.t.class, new kg());
        gu.Jf().put(a.c.class, new hz());
        gu.Jf().put(au.b.class, new bl());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.d.class, new bs());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.e.class, new ce());
        gu.Jf().put(av.a.class, new bt());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.o.class, new ii());
        gu.Jf().put(m.b.class, new ge());
        gu.Jf().put(as.a.class, new ip());
        gu.Jf().put(d.b.class, new mi());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.q.class, new iv());
        gu.Jf().put(a.C0563a.class, new am());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.b.class, new bm());
        gu.Jf().put(com.kwad.sdk.a.a.a.a.class, new gf());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.s.class, new kf());
        gu.Jf().put(ak.a.class, new fr());
        gu.Jf().put(f.a.class, new fc());
        gu.Jf().put(a.b.class, new jz());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.g.class, new cp());
        gu.Jf().put(v.b.class, new lb());
        gu.Jf().put(com.kwad.components.core.innerEc.followuser.a.class, new eq());
        gu.Jf().put(ah.a.class, new iz());
        gu.Jf().put(WebCardRegisterLiveMessageListener.AdLiveMessageInfoList.class, new ad());
        gu.Jf().put(g.a.class, new fd());
        gu.Jf().put(bg.a.class, new fp());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.p.class, new in());
        gu.Jf().put(WarmUpReportMessage.class, new mp());
        gu.Jf().put(a.b.class, new du());
        gu.Jf().put(j.b.class, new fh());
        gu.Jf().put(com.kwad.components.core.offline.moitor.b.class, new ig());
        gu.Jf().put(UaidInfo.class, new ly());
        gu.Jf().put(com.kwad.components.core.video.a.e.class, new mq());
        gu.Jf().put(InnerEcUserLoginBindInfo.class, new ga());
        gu.Jf().put(q.a.class, new ho());
        gu.Jf().put(WebCardRegisterLiveShopListener.AdLiveItemShopInfo.class, new ac());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.h.class, new dk());
        gu.Jf().put(ap.a.class, new gp());
        gu.Jf().put(com.kwad.components.core.webview.tachikoma.c.f.class, new cm());
        gu.Jf().put(WebCardVideoPositionHandler.VideoPosition.KSAdJSCornerModel.class, new gw());
        gu.Jf().put(a.C0562a.class, new dr());
    }
}
