package com.kwad.sdk.core.config;

import com.kwad.sdk.core.config.item.InstallActivateReminderConfigItem;
import com.kwad.sdk.core.config.item.TipsConfigItem;
import com.kwad.sdk.core.config.item.f;
import com.kwad.sdk.core.config.item.g;
import com.kwad.sdk.core.config.item.h;
import com.kwad.sdk.core.config.item.i;
import com.kwad.sdk.core.config.item.j;
import com.kwad.sdk.core.config.item.k;
import com.kwad.sdk.core.config.item.l;
import com.kwad.sdk.core.config.item.m;
import com.kwad.sdk.core.config.item.n;
import com.kwad.sdk.core.config.item.o;
import com.kwad.sdk.core.config.item.p;
import com.kwad.sdk.core.config.item.q;
import com.kwad.sdk.core.config.item.r;
import com.kwad.sdk.core.config.item.s;
import com.kwad.sdk.core.config.item.t;
import java.util.ArrayList;

/* JADX INFO: compiled from: SearchBox */
/* JADX INFO: loaded from: classes9.dex */
public final class c {
    public static final com.kwad.sdk.core.config.item.d aDf = new com.kwad.sdk.core.config.item.d("tkRenderTypeSwitch", false);
    public static final p aDg = new p("feedTKIdleTime", 0L);
    public static l aDh = new l("batchReportCatchLimit", 20);
    public static l aDi = new l("exceptionCollectorSwitch", 1);
    public static l aDj = new l("catchExceptionReportSwitch", 1);
    public static l aDk = new l("mediaPlayerLogReport", 0);
    public static l aDl = new l("didCopySwitch", 1);
    public static l aDm = new l("enableHodor", 0);
    public static l aDn = new l("speedLimitSwitch", 1);
    public static l aDo = new l("speedLimitThreshold", 200);
    public static l aDp = new l("ksNativeAdCustomSwitch", 0);
    public static l aDq = new l("compoAndSoThreadPoolCoreSize", 0);
    public static l aDr = new l("forceActivateAfterInstalled", 0);
    public static l aDs = new l("spliceVideoInteractionType", 0);
    public static l aDt = new l("feedLoadOptimizeType", 0);
    public static l aDu = new l("feedLoadOptimizeExternalEnable", 0);
    public static l aDv = new l("nativeAdSlideClickDisable", 0);
    public static s aDw = new s("uaid", "");
    public static p aDx = new p("uaidExpireSec", 0L);
    public static p aDy = new p("uaidRequestDelayTime", 5L);
    public static l aDz = new l("interstitialAdLoadProcessChange", 0);
    public static l aDA = new l("interstitialAdActivityOpt", 0);
    public static l aDB = new l("formAdExitInterceptSwitch", 0);
    public static l aDC = new l("adLeaveConfirmSwitch", 0);
    public static l aDD = new l("viewLandingPageTaskDuration", 15);
    public static l aDE = new l("rewardAdVideoPreCacheSize", 800);
    public static com.kwad.sdk.core.config.item.d aDF = new com.kwad.sdk.core.config.item.d("dataFlowAutoStartSwitch", false);
    public static p aDG = new p("deviceInfoDisableConfig", 0L);
    public static com.kwad.sdk.core.config.item.d aDH = new com.kwad.sdk.core.config.item.d("playerEnable", false);
    public static com.kwad.sdk.core.config.item.d aDI = new com.kwad.sdk.core.config.item.d("dynamicEnable", false);
    public static com.kwad.sdk.core.config.item.d aDJ = new com.kwad.sdk.core.config.item.d("commercialLoggerDeviceSwitch", false);
    public static l aDK = new l("commercialLoggerSwitch", 1);
    public static s aDL = new s("tkSoUrlV7a", "");
    public static s aDM = new s("tkSoUrlV8a", "");
    public static com.kwad.sdk.core.config.item.d aDN = new com.kwad.sdk.core.config.item.d("useTKSoAll", false);
    public static n aDO = new n("playerConfig", null);
    public static t aDP = new t("pkgNameList", new ArrayList(0));
    public static t aDQ = new t("hostList", new ArrayList(0));
    public static t aDR = new t("crashGatherRateConfigList", new ArrayList(0));
    public static TipsConfigItem aDS = new TipsConfigItem();
    public static com.kwad.sdk.core.config.item.c aDT = new com.kwad.sdk.core.config.item.c();
    public static InstallActivateReminderConfigItem aDU = new InstallActivateReminderConfigItem();
    public static f aDV = new f();
    public static com.kwad.sdk.core.config.item.e aDW = new com.kwad.sdk.core.config.item.e();
    public static m<Integer> aDX = new m<>("adTKGrayConfig");
    public static q aDY = new q("realtimeReportActions", "");
    public static r aDZ = new r();
    public static l aEa = new l("appInstallNoticeSecond", 0);
    public static l aEb = new l("installFloatingLayerPostion", 0);
    public static l aEc = new l("remindInstallStyle", 0);
    public static l aEd = new l("remindInstallTime", 60);
    public static l aEe = new l("watermarkKwaiIdSwitch", 0);
    public static l aEf = new l("insertScreenV2Switch", 0);
    public static l aEg = new l("insertScreenAutoPlaySwitch", 0);
    public static k aEh = new k("insertScreenV2ShowConfig");
    public static l aEi = new l("environmentDetectEnable", 0);
    public static l aEj = new l("simCardInfoEnable", 0);
    public static l aEk = new l("baseStationEnable", 0);
    public static l aEl = new l("sensorEventEnable2", 0);
    public static l aEm = new l("lpAutoDownloadApkSwitch", 1);
    public static l aEn = new l("autoDownloadUrlSwitch", 0);
    public static l aEo = new l("insertScreenAdType", 0);
    public static l aEp = new l("interstitialAutoCallAppCountDaily", 1);
    public static l aEq = new l("mediaControlPlaySwitch", 1);
    public static s aEr = new s("appStatusSoUrlV7a", "");
    public static s aEs = new s("appStatusSoUrlV8a", "");
    public static s aEt = new s("appStatusSoVersion", "");
    public static l aEu = new l("deeplinkCheckSwitch", -3);
    public static com.kwad.sdk.core.config.item.d aEv = new com.kwad.sdk.core.config.item.d("deeplinkWindowSwitch", false);
    public static i aEw = new i();
    public static com.kwad.sdk.core.config.item.d aEx = new com.kwad.sdk.core.config.item.d("adLiveSwitch", false);
    public static com.kwad.sdk.core.config.item.d aEy = new com.kwad.sdk.core.config.item.d("TKSwitch", true);
    public static s aEz = new s("TKSwitchExtra", "");
    public static com.kwad.sdk.core.config.item.d aEA = new com.kwad.sdk.core.config.item.d("llsidDisplaySwitch", true);
    public static com.kwad.sdk.core.config.item.d aEB = new com.kwad.sdk.core.config.item.d("TKJsonSubThread", true);
    public static com.kwad.sdk.core.config.item.d aEC = new com.kwad.sdk.core.config.item.d("reduceDeviceSigSwitch", true);
    public static com.kwad.sdk.core.config.item.d aED = new com.kwad.sdk.core.config.item.d("personalRecommend", false);
    public static l aEE = new l("forceActivate", 0);
    public static l aEF = new l("remindOpen", -1);
    public static com.kwad.sdk.core.config.item.d aEG = new com.kwad.sdk.core.config.item.d("viewVisibleCheckLegacy", false);
    public static s aEH = new s("nativeAndAnrDynamic", "");
    public static l aEI = new l("kwaiAppVersionSwitch", 1);
    public static com.kwad.sdk.core.config.item.d aEJ = new com.kwad.sdk.core.config.item.d("disableLogcatOAID", false);
    public static s aEK = new s("userAgent");
    public static l aEL = new l("biddingLogSwitch", 0);
    public static l aEM = new l("forceActiveThreshold", 5);
    public static l aEN = new l("forceActiveInterval", 3);
    public static l aEO = new l("hybridEnable", 1);
    public static com.kwad.sdk.core.config.item.d aEP = new com.kwad.sdk.core.config.item.d("wifiResumeDownload", false);
    public static h aEQ = new h("adExposureAreaPercent", 0.3f);
    public static h aER = new h("adExposureTime", -1.0f);
    public static h aES = new h("drawAdExposureAreaPercent", 0.7f);
    public static h aET = new h("apmToRECommercialRatio", 0.0f);
    public static com.kwad.sdk.core.config.item.d aEU = new com.kwad.sdk.core.config.item.d("appInAdExposureBlacklist", false);
    public static com.kwad.sdk.core.config.item.d aEV = new com.kwad.sdk.core.config.item.d("soDownloadBreakpointContinuation", true);
    public static l aEW = new l("soLoadMaxRetryCount", 1);
    public static com.kwad.sdk.core.config.item.d aEX = new com.kwad.sdk.core.config.item.d("feedAdForceGetAudioFocus", false);
    public static com.kwad.sdk.core.config.item.d aEY = new com.kwad.sdk.core.config.item.d("forceGetAudioFocus", false);
    public static l aEZ = new l("feedAdWebviewOptimize", 1);
    public static com.kwad.sdk.core.config.item.d aFa = new com.kwad.sdk.core.config.item.d("logCommandSwitch", false);
    public static com.kwad.sdk.core.config.item.d aFb = new com.kwad.sdk.core.config.item.d("logRecordAllSwitch", false);
    public static p aFc = new p("obiwanLogFilesDiskQuota", 52428800L);
    public static n aFd = new n("logCommandResult", "", false);
    public static p aFe = new p("validClickConvertTime", 1000L);
    public static com.kwad.sdk.core.config.item.d aFf = new com.kwad.sdk.core.config.item.d("eplCommandSwitch", false);
    public static l aFg = new l("playableAutoPlayEnable", 1);
    public static l aFh = new l("netMonitorSwitch", 0);
    public static com.kwad.sdk.core.config.item.d aFi = new com.kwad.sdk.core.config.item.d("ipDirectEnable", false);
    public static com.kwad.sdk.core.config.item.d aFj = new com.kwad.sdk.core.config.item.d("ipPreferEnable", false);
    public static l aFk = new l("weaponSwitch", 1);
    public static l aFl = new l("kvModeV2", 0);
    public static j aFm = new j();
    public static l aFn = new l("idcRollbackInterval", 0);
    public static p aFo = new p("currentServerTimeMs");
    public static l aFp = new l("clientProofreadTimeErrorRangeHours", 100);
    public static h aFq = new h("adTraceReportRate", 1.0f);
    public static l aFr = new l("adTraceRepeatEnable", 0);
    public static l aFs = new l("appHeartBeatInterval", 0);
    public static l aFt = new l("insertShowPercent", 100);
    public static l aFu = new l("adCacheCode", 0);
    public static s aFv = new s("installTipsContentDesc", "");
    public static s aFw = new s("installTipsPositiveActionDesc", "");
    public static s aFx = new s("installTipsNegativeActionDesc", "");
    public static com.kwad.sdk.core.config.item.d aFy = new com.kwad.sdk.core.config.item.d("threadOptEnable", false);
    public static com.kwad.sdk.core.config.item.d aFz = new com.kwad.sdk.core.config.item.d("resourceWarmupSwitch", false);
    public static l aFA = new l("resourceWarmupDelayTime", 5);
    public static s aFB = new s("perfMonitorV2", "");
    public static l aFC = new l("neoVideoAdaptStrategy", 1);
    public static l aFD = new l("feedTKLoadTimeOut", 2500);
    public static l aFE = new l("drawTKLoadTimeOut", 2000);
    public static com.kwad.sdk.core.config.item.d aFF = new com.kwad.sdk.core.config.item.d("adCacheOptEnable", false);
    public static l aFG = new l("adImageLoaderCacheLimitSize", -1);
    public static com.kwad.sdk.core.config.item.d aFH = new com.kwad.sdk.core.config.item.d("autoShowActivityMiddlePage", false);
    public static l aFI = new l("videoCacheOpt", 0);
    public static s aFJ = new s("ranger", "");
    public static l aFK = new l("hdrConfig", 0);
    public static s aFL = new s("packageInstall", "");
    public static s aFM = new s("eplV1", "");
    public static s aFN = new s("threadPoolPerfMonitor", "");
    public static s aFO = new s("threadPoolParams", "");
    public static g aFP = new g("crashUploadRate", Double.valueOf(1.0d));
    public static g aFQ = new g("adFeedWidthMinPercent", Double.valueOf(0.3d));
    public static com.kwad.sdk.core.config.item.d aFR = new com.kwad.sdk.core.config.item.d("videoPerfMonitor", false);
    public static com.kwad.sdk.core.config.item.d aFS = new com.kwad.sdk.core.config.item.d("enableHookPluginResource", true);
    public static com.kwad.sdk.core.config.item.d aFT = new com.kwad.sdk.core.config.item.d("enableHookWrapperContext", true);
    public static com.kwad.sdk.core.config.item.d aFU = new com.kwad.sdk.core.config.item.d("batchReportSkipJSONParseEnable", false);
    public static com.kwad.sdk.core.config.item.d aFV = new com.kwad.sdk.core.config.item.d("enableAdTrackLog", true);
    public static com.kwad.sdk.core.config.item.d aFW = new com.kwad.sdk.core.config.item.d("usePolicy64LevelDisable", false);
    public static com.kwad.sdk.core.config.item.d aFX = new com.kwad.sdk.core.config.item.d("tkReportInfoSwitch", false);
    public static l aFY = new l("tubeRenderType", 0);
    public static l aFZ = new l("useTKAdBrowse", 0);
    public static com.kwad.sdk.core.config.item.d aGa = new com.kwad.sdk.core.config.item.d("enableMediaGetAdInfo", false);
    public static com.kwad.sdk.core.config.item.d aGb = new com.kwad.sdk.core.config.item.d("ecExtInfoSwitch", false);
    public static s aGc = new s("trackBlackUrlConfig", "");
    public static l aGd = new l("tkMemCacheSize", 0);
    public static t aGe = new t("preloadMemCacheTemplateIds", new ArrayList(0));
    public static l aGf = new l("kGeoInfoConfig", 1);
    public static l aGg = new l("appMonitorSwitch", 0);
    public static l aGh = new l("videoCacheErrorCallbackSwitch", 0);
    public static l aGi = new l("tkErrorDetailCount", 1);
    public static l aGj = new l("videoLaunchOptimiseSwitch", 0);
    public static l aGk = new l("enableInitStartMode", 1);
    public static s aGl = new s("localLogConfig", "");
    public static s aGm = new s("adLogRetryConfig", "");
    public static o aGn = new o("dpSchemeFlags");
    public static com.kwad.sdk.core.config.item.d aGo = new com.kwad.sdk.core.config.item.d("feedAdBgTransparentSwitch");
    public static l aGp = new l("adRequestNum", 1);
    public static l aGq = new l("carouselInterval", 30000);
    public static p aGr = new p("packageInfoLimiter", 0L);
    public static com.kwad.sdk.core.config.item.d aGs = new com.kwad.sdk.core.config.item.d("showOptimizedProgress");
    public static l aGt = new l("optimizeProgressMethod", 0);
    public static l aGu = new l("splashLoadTimeOptimize", 0);
    public static p aGv = new p("splashVisibleCheckDelayTime", 500L);
    public static com.kwad.sdk.core.config.item.d aGw = new com.kwad.sdk.core.config.item.d("isWaynePlayerValid", false);
    public static com.kwad.sdk.core.config.item.d aGx = new com.kwad.sdk.core.config.item.d("isWaynePlayerAsDefaultPlayer", false);
    public static n aGy = new n("waynePlayerPlayConfig", null);
    public static l aGz = new l("waynePlayerSupportAndroidApi", 24);
    public static com.kwad.sdk.core.config.item.d aGA = new com.kwad.sdk.core.config.item.d("apkBroadcastReceiverSwitch", true);
    public static com.kwad.sdk.core.config.item.d aGB = new com.kwad.sdk.core.config.item.d("closureSwitch", false);
    public static com.kwad.sdk.core.config.item.d aGC = new com.kwad.sdk.core.config.item.d("closureVideoTwoSwitch", false);
    public static s aGD = new s("closureH5AuthUrl", "");
    public static s aGE = new s("closureH5AuthAppId", "");
    public static s aGF = new s("closureH5AuthPathPart", "");
    public static s aGG = new s("closureSupportSdkVersion", "4.8.30");
    public static com.kwad.sdk.core.config.item.d aGH = new com.kwad.sdk.core.config.item.d("enableThreadOpt2", false);
    public static n aGI = new n("cheatInfoConfig", null);
    public static n aGJ = new n("featureCollectConfig", null);
    public static final l aGK = new l("installerCheckPkgAbSwitch", 0);
    public static final s aGL = new s("installerCheckExtraPkgs", "");
    public static final l aGM = new l("probeBatch", 0);
    public static s aGN = new s("thKwaiMarketUrl", "");

    public static void init() {
    }
}
